### ISSUE TITLE
Hakyll 4.7 support

### ISSUE THREAD

**Issue by codylwalker** [wetmore/personal-site#1]
`ghc --make site.hs` gives the following:

``` shell
CustomCompilers.hs:28:55:
    Couldn't match expected type ‘Item Pandoc’
                with actual type ‘Compiler (Item Pandoc)’
    In the second argument of ‘withItemBody’, namely ‘pandoc’
    In a stmt of a 'do' block:
      withItemBody (unsafeCompiler . customWriter wopt) pandoc

CustomCompilers.hs:35:13:
    Couldn't match type ‘Compiler (Item Pandoc)’ with ‘Item Pandoc’
    Expected type: Compiler (Item Pandoc) -> Compiler (Item String)
      Actual type: Item Pandoc -> Compiler (Item String)
    In the second argument of ‘(>>=)’, namely
      ‘withItemBody (unsafeCompiler . customWriter wopt)’
    In the expression:
      (readPandocWith ropt <$> getResourceBody)
      >>= withItemBody (unsafeCompiler . customWriter wopt)
```

**Comment by wetmore** [comment]
I'll look at this when I get home. As an aside, how did you find this repo?

**Comment by wetmore** [comment]
Actually it should be pretty easy to fix. I believe you should be able to fix it by changing 

`readPandocWith ropt <$> getResourceBody`

to

`readPandocWith ropt =<< getResourceBody`

in both functions which use it. There are two functions there which do the same thing because I wasn't sure which style I preferred at the time. In the next release I'll get rid of the latter.

Note that with the change above, you should be able to rewrite the function as

``` haskell
customWriterCompilerWith :: (WriterOptions -> Pandoc -> IO String)
                         -> ReaderOptions -> WriterOptions
                         -> Compiler (Item String)
customWriterCompilerWith customWriter ropt wopt = do
    body <- getResourceBody
    pandoc <- readPandocWith ropt body
    withItemBody (unsafeCompiler . customWriter wopt) pandoc
```

Does this fix it?

**Comment by codylwalker** [comment]
That worked! 
(I also had to rename customCompiler.hs to CustomCompiler.hs)

I found this repo from your blog. I found your blog by looking at hakyll sites with footnotes, and I really liked the way you've laid them out. The site looks great too - very clean. Well done!

Thanks for the fix.

**Comment by wetmore** [comment]
Interesting, I put it up on github for hosting but didn't expect anyone else to use it, so there isn't any concept of releases yet. This means there is some half-finished code lying around. For example, there is a mostly-complete implementation of support for named collections of posts (sort of like tags, but with the concept of "first in collection", "second in collection") but since I haven't written anything which needs them there are some parts which aren't complete.

Anyway, happy to hear the fix worked.
